{% set name = "pyct-core" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyct/pyct-{{ version }}.tar.gz
  sha256: dd9f4ac5cbd8e37c352c04036062d3c5f67efec76d404761ef16b0cbf26aa6a0

build:
  entry_points:
    - pyct=pyct.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  run_constrained:
    - pyct {{ version }}
  host:
    - python >=3.7
    - param >=1.7.0
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - param >=1.7.0
    # cli
    - pyyaml
    - requests

test:
  imports:
    - pyct
  commands:
    - pip check
    - pyct --help
  requires:
    - pip

about:
  home: https://github.com/pyviz/pyct
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Common tasks for package building (e.g. bundle examples)
  doc_url: https://github.com/pyviz/pyct#pyctbuild
  dev_url: https://github.com/pyviz/pyct

extra:
  recipe-maintainers:
    - ceball
