{% set name = "pyct-core" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyct/pyct-{{ version }}.tar.gz
  sha256: dd9f4ac5cbd8e37c352c04036062d3c5f67efec76d404761ef16b0cbf26aa6a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  run_constrained:
    - pyct {{ version }}
  host:
    - python
    - pip
    - param >=1.7.0
  run:
    - python
    - param >=1.7.0

test:
  imports:
    - pyct
    - pyct.build

about:
  home: https://github.com/pyviz/pyct
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Common tasks for package building (e.g. bundle examples)
  doc_url: https://github.com/pyviz/pyct#pyctbuild
  dev_url: https://github.com/pyviz/pyct

extra:
  recipe-maintainers:
    - ceball
